# Generated by Django 4.2.7 on 2025-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDNModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('yolon-artirilmisVeri', 'YOLO N Enhanced Data'), ('yolos-artirilmisVeri', 'YOLO S Enhanced Data'), ('yolom-artirilmisVeri', 'YOLO M Enhanced Data')], max_length=50, unique=True)),
                ('cdn_url', models.URLField()),
                ('input_size', models.IntegerField(default=224)),
                ('classification_layer', models.CharField(default='classification', max_length=100)),
                ('feature_layers', models.TextField(default='features,layer1,layer2,layer3', help_text='Comma-separated list of layers to use for Score-CAM')),
                ('batch_size', models.IntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CDN Model',
                'verbose_name_plural': 'CDN Models',
            },
        ),
    ]
