# Generated by Django 4.2.7 on 2025-09-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnmodel',
            name='feature_layers',
            field=models.JSONField(default=dict, help_text='JSON object with layer names as keys and spatial dimensions as values. Format: {"layer_name": {"width": 112, "height": 112}, ...}'),
        ),
    ]
