# Generated by Django 4.2.7 on 2025-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_alter_cdnmodel_feature_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnmodel',
            name='model_type',
            field=models.CharField(choices=[('yolon-artirilmisVeri-ONNX', 'YOLO N Enhanced Data ONNX Format'), ('yolon-artirilmisVeri-ORT', 'YOLO N Enhanced Data ORT Format'), ('yolos-artirilmisVeri', 'YOLO S Enhanced Data'), ('yolom-artirilmisVeri', 'YOLO M Enhanced Data')], max_length=50, unique=True),
        ),
    ]
