# Generated by Django 4.2.7 on 2025-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0004_alter_cdnmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnmodel',
            name='classes',
            field=models.JSONField(blank=True, default=list, help_text="List of classes, format: ['CLASS1', 'CLASS2',...]"),
        ),
    ]
